name: EC2 Auto Deployment

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Workflow triggered at $(date)" >> /home/ec2-user/deploy-log.txt
            cd /usr/share/nginx/html/chron-jobs
            git pull origin main
            sudo cp index.html /usr/share/nginx/html/
            sudo systemctl restart nginx
